server:
  port: 8585
  
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userRegDB?createDatabaseIfNotExist=true
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
    separator: $$
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      
